export default {
  WELCOME: "WELCOME",
  MAIN_NAVIGATION: {
    INDEX: "MAIN_NAVIGATION",
    NAVIGATOR: "NAVIGATOR",
    HOME: {
      INDEX: "HOME",
      CREATE_CLEEP: "CREATE_CLEEP",
      JOIN_CLEEP: "JOIN_CLEEP",
      CLEEP_LIST: "CLEEP_LIST",
      ADD_CLEEP: "ADD_CLEEP",
      EDIT_CLEEP: "EDIT_CLEEP",
    },
    SETTINGS: "SETTINGS",
    DEVICES: "DEVICES",
  },
};
